version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    expose:
      - "3000"

  nginx:
    build:
      context: ./pigfun.online_nginx
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
